### ISSUE TITLE
TryFSharp Milestone 1

### ISSUE THREAD

**Issue by AviAvni** [tryfsharp/tryfsharp#13]
- [ ] https://github.com/tryfsharp/tryfsharp/issues/10
- [ ] https://github.com/tryfsharp/tryfsharp/issues/11
- [ ] https://github.com/tryfsharp/tryfsharp/issues/12
- [ ] Initial url try.fsharp.org
- [ ] final url  tryfsharp.org @ReedCopsey
- [ ] testing start at the end of Feb
- [ ] ship date end of Mars (@mathias-brandewinder birthday 😄)
